[2025-02-01T01:28:42.525+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T01:28:42.618+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.bot_ex_bbva manual__2025-02-01T01:28:38.016305+00:00 [queued]>
[2025-02-01T01:28:42.655+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.bot_ex_bbva manual__2025-02-01T01:28:38.016305+00:00 [queued]>
[2025-02-01T01:28:42.657+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T01:28:42.723+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): bot_ex_bbva> on 2025-02-01 01:28:38.016305+00:00
[2025-02-01T01:28:42.741+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=510) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T01:28:42.752+0000] {standard_task_runner.py:72} INFO - Started process 511 to run task
[2025-02-01T01:28:42.747+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'bot_ex_bbva', 'manual__2025-02-01T01:28:38.016305+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpcr0t3p9p']
[2025-02-01T01:28:42.757+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask bot_ex_bbva
[2025-02-01T01:28:42.957+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.bot_ex_bbva manual__2025-02-01T01:28:38.016305+00:00 [running]> on host 56024cb05cfe
[2025-02-01T01:28:43.408+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='bot_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T01:28:38.016305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T01:28:38.016305+00:00'
[2025-02-01T01:28:43.413+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T01:28:43.515+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-01T01:28:43.520+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/bot_etl_ex_bbva.py']
[2025-02-01T01:28:43.560+0000] {subprocess.py:99} INFO - Output:
[2025-02-01T01:28:46.278+0000] {subprocess.py:106} INFO - 2025-02-01 01:28:46,277 - bot_etl_ex_bbva - ERROR - Error Loading Cerrados.xlsx to ETL:
[2025-02-01T01:28:46.279+0000] {subprocess.py:106} INFO - ***Error type:*** AttributeError
[2025-02-01T01:28:46.281+0000] {subprocess.py:106} INFO - ***Error message:*** 'Logger' object has no attribute 'inf'
[2025-02-01T01:28:46.283+0000] {subprocess.py:106} INFO - ***Full Traceback:*** Traceback (most recent call last):
[2025-02-01T01:28:46.285+0000] {subprocess.py:106} INFO -   File "/opt/***/scripts/bot_etl_ex_bbva.py", line 50, in main
[2025-02-01T01:28:46.286+0000] {subprocess.py:106} INFO -     logger.inf("Bot ETL Exito-BBVA started")
[2025-02-01T01:28:46.288+0000] {subprocess.py:106} INFO -     ^^^^^^^^^^
[2025-02-01T01:28:46.289+0000] {subprocess.py:106} INFO - AttributeError: 'Logger' object has no attribute 'inf'. Did you mean: 'info'?
[2025-02-01T01:28:46.291+0000] {subprocess.py:106} INFO - 
[2025-02-01T01:28:46.293+0000] {subprocess.py:106} INFO - 2025-02-01 01:28:46,278 - bot_etl_ex_bbva - INFO - bot_etl_ex_bbva finish execution
[2025-02-01T01:28:46.428+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-01T01:28:46.507+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T01:28:46.509+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=bot_ex_bbva, run_id=manual__2025-02-01T01:28:38.016305+00:00, execution_date=20250201T012838, start_date=20250201T012842, end_date=20250201T012846
[2025-02-01T01:28:46.601+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T01:28:46.645+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T01:28:46.651+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
