[2025-02-04T01:30:01.983-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T01:30:02.005-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-03T06:30:00+00:00 [queued]>
[2025-02-04T01:30:02.016-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-03T06:30:00+00:00 [queued]>
[2025-02-04T01:30:02.018-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-04T01:30:02.042-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_bot_como_vamos> on 2025-02-03 06:30:00+00:00
[2025-02-04T01:30:02.050-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=21691) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T01:30:02.052-0500] {standard_task_runner.py:72} INFO - Started process 21692 to run task
[2025-02-04T01:30:02.052-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'task_bot_como_vamos', 'scheduled__2025-02-03T06:30:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpnr9aopzs']
[2025-02-04T01:30:02.054-0500] {standard_task_runner.py:105} INFO - Job 31: Subtask task_bot_como_vamos
[2025-02-04T01:30:02.113-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos scheduled__2025-02-03T06:30:00+00:00 [running]> on host 21f1c1b48730
[2025-02-04T01:30:02.216-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='task_bot_como_vamos' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T06:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T06:30:00+00:00'
[2025-02-04T01:30:02.218-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T01:30:02.245-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-04T01:30:02.248-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/bot_reporte_como_vamos.py']
[2025-02-04T01:30:02.262-0500] {subprocess.py:99} INFO - Output:
[2025-02-04T01:30:05.129-0500] {subprocess.py:106} INFO - ic| report_date: '03/02/2025'
[2025-02-04T01:30:05.130-0500] {subprocess.py:106} INFO - 2025-02-04 01:30:05,129 - bot_como_vamos - INFO - Starting script bot_como_vamos.py
[2025-02-04T01:30:05.919-0500] {subprocess.py:106} INFO - 2025-02-04 01:30:05,918 - bot_como_vamos - INFO - Conexi√≥n al Selenium Hub establecida correctamente
[2025-02-04T01:31:01.928-0500] {subprocess.py:106} INFO - ic| login_success: <selenium.webdriver.remote.webelement.WebElement (session="23fb968773e919deda44e4ff89073c55", element="f.CB50044FA9025E76AE80C2D94A1DACA3.d.0183FA220F203FACC99E71DBB9344A24.e.76")>
[2025-02-04T01:31:01.929-0500] {subprocess.py:106} INFO - 2025-02-04 01:31:01,928 - bot_como_vamos - INFO - Loging success
[2025-02-04T01:31:12.061-0500] {subprocess.py:106} INFO - 2025-02-04 01:31:12,061 - bot_como_vamos - INFO - Click in menu button successfully
[2025-02-04T01:31:22.244-0500] {subprocess.py:106} INFO - 2025-02-04 01:31:22,244 - bot_como_vamos - INFO - Input dates successfully
[2025-02-04T01:31:32.393-0500] {subprocess.py:106} INFO - 2025-02-04 01:31:32,393 - bot_como_vamos - INFO - Click in 'Empresas Y Negocios' successfully
[2025-02-04T01:31:55.935-0500] {subprocess.py:106} INFO - 2025-02-04 01:31:55,935 - assets - INFO - Waiting for download file...............
[2025-02-04T01:31:55.977-0500] {subprocess.py:106} INFO - ic| file: '.com.google.Chrome.Tzvghm'
[2025-02-04T01:32:00.983-0500] {subprocess.py:106} INFO - ic| file: 'Reporte como_vamos.xlsx'
[2025-02-04T01:32:00.984-0500] {subprocess.py:106} INFO - 2025-02-04 01:32:00,983 - bot_como_vamos - INFO - Download Reporte como_vamos succesfully
[2025-02-04T01:32:01.421-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-04T01:32:01.471-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T01:32:01.472-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=task_bot_como_vamos, run_id=scheduled__2025-02-03T06:30:00+00:00, execution_date=20250203T063000, start_date=20250204T063002, end_date=20250204T063201
[2025-02-04T01:32:01.501-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T01:32:01.532-0500] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-04T01:32:01.542-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
