[2025-02-14T06:33:02.789-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T06:33:02.806-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.clean_files scheduled__2025-02-13T11:30:00+00:00 [queued]>
[2025-02-14T06:33:02.814-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.clean_files scheduled__2025-02-13T11:30:00+00:00 [queued]>
[2025-02-14T06:33:02.816-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-14T06:33:02.830-0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): clean_files> on 2025-02-13 11:30:00+00:00
[2025-02-14T06:33:02.837-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=61486) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T06:33:02.839-0500] {standard_task_runner.py:72} INFO - Started process 61487 to run task
[2025-02-14T06:33:02.840-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'clean_files', 'scheduled__2025-02-13T11:30:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmp2j84wy97']
[2025-02-14T06:33:02.841-0500] {standard_task_runner.py:105} INFO - Job 126: Subtask clean_files
[2025-02-14T06:33:02.898-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.clean_files scheduled__2025-02-13T11:30:00+00:00 [running]> on host 21f1c1b48730
[2025-02-14T06:33:02.994-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='clean_files' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-13T11:30:00+00:00'
[2025-02-14T06:33:02.995-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T06:33:03.020-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T06:33:03.033-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T06:33:03.034-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=clean_files, run_id=scheduled__2025-02-13T11:30:00+00:00, execution_date=20250213T113000, start_date=20250214T113302, end_date=20250214T113303
[2025-02-14T06:33:03.096-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T06:33:03.113-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T06:33:03.117-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
